# Generated by Django 5.2.17 on 2026-10-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_catalogimportreceipt'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='catalogitem',
            constraint=models.UniqueConstraint(fields=('id', 'organization'), name='catalog_id_org_unique'),
        ),
    ]
