# Generated by Django 5.2.17 on 2026-10-05 15:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderdocument'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDocumentReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(blank=True, default='', max_length=255)),
                ('extracted_order_number', models.CharField(blank=True, default='', max_length=64)),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('grand_total', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=18)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('needs_review', 'Needs review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='needs_review', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_document_reviews', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='orders.orderdocument')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_document_reviews', to='organizations.organization')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('vendor_name__regex', '\\S'), ('vendor_name', ''), _connector='OR'), name='orderdocumentreview_vendor_name_optional'), models.CheckConstraint(condition=models.Q(('extracted_order_number__regex', '\\S'), ('extracted_order_number', ''), _connector='OR'), name='orderdocumentreview_number_optional'), models.CheckConstraint(condition=models.Q(('grand_total__gte', 0)), name='orderdocumentreview_total_nonnegative')],
            },
        ),
    ]
