# Generated by Django 5.2.17 on 2026-10-06 08:00

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_catalogitem_catalog_id_org_unique'),
        ('orders', '0005_order_tenant_boundary'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft')], default='draft', max_length=16)),
                ('source_type', models.CharField(choices=[('manual', 'Manual')], default='manual', max_length=16)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_reference', models.CharField(blank=True, default='', max_length=128)),
                ('original_intake_text', models.TextField(blank=True, default='', max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiating_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_draft_orders', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_orders', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='DraftOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('requested_sku', models.TextField(blank=True, default='')),
                ('requested_description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001')), django.core.validators.MaxValueValidator(Decimal('999999999.999'))])),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('catalogue_sku_snapshot', models.TextField(blank=True, default='')),
                ('catalogue_description_snapshot', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalogue_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='draft_order_lines', to='catalog.catalogitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_lines', to='orders.draftorder')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_order_lines', to='organizations.organization')),
            ],
        ),
        migrations.AddConstraint(
            model_name='draftorder',
            constraint=models.UniqueConstraint(fields=('id', 'organization'), name='draftorder_id_org_unique'),
        ),
        migrations.AddConstraint(
            model_name='draftorder',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft')), name='draftorder_status_draft'),
        ),
        migrations.AddConstraint(
            model_name='draftorder',
            constraint=models.CheckConstraint(condition=models.Q(('source_type', 'manual')), name='draftorder_source_manual'),
        ),
        migrations.AddConstraint(
            model_name='draftorder',
            constraint=models.CheckConstraint(condition=models.Q(('customer_name', ''), ('customer_name__regex', '\\S'), _connector='OR'), name='draftorder_customer_optional_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='draftorder',
            constraint=models.CheckConstraint(condition=models.Q(('customer_reference', ''), ('customer_reference__regex', '\\S'), _connector='OR'), name='draftorder_reference_optional_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='draftorder',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('original_intake_text'), 10000), name='draftorder_original_text_bounded'),
        ),
        migrations.AddConstraint(
            model_name='draftorderline',
            constraint=models.UniqueConstraint(fields=('order', 'position'), name='draftline_order_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='draftorderline',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='draftline_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='draftorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__isnull', True), models.Q(('quantity__gt', 0), ('quantity__lte', Decimal('999999999.999'))), _connector='OR'), name='draftline_quantity_valid'),
        ),
        migrations.AddConstraint(
            model_name='draftorderline',
            constraint=models.CheckConstraint(condition=models.Q(('requested_sku__regex', '\\S'), ('requested_description__regex', '\\S'), models.Q(('catalogue_item__isnull', False), ('catalogue_sku_snapshot__regex', '\\S')), _connector='OR'), name='draftline_identity_present'),
        ),
        migrations.AddConstraint(
            model_name='draftorderline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('catalogue_description_snapshot', ''), ('catalogue_item__isnull', True), ('catalogue_sku_snapshot', '')), models.Q(('catalogue_item__isnull', False), ('catalogue_sku_snapshot__regex', '\\S')), _connector='OR'), name='draftline_catalogue_snapshot_valid'),
        ),
    ]
