# Generated by Django 5.2.17 on 2026-10-09 00:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_draft_conversion'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdocument',
            name='source_sha256',
            field=models.CharField(blank=True, db_default='', default='', editable=False, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='orderdocument',
            constraint=models.CheckConstraint(condition=models.Q(('source_sha256__regex', '^[0-9a-f]{64}$'), models.Q(('source_sha256', ''), models.Q(('file__startswith', 'intake/'), _negated=True)), _connector='OR'), name='orderdocument_private_source_digest'),
        ),
    ]
