# Generated by Django 5.2.17 on 2026-10-05 08:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


def require_postgresql(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        raise RuntimeError("The catalogue RLS migration requires PostgreSQL.")


ROLE_GUARD = """
DO $$
BEGIN
    IF current_user <> 'orderdesk_migrator' THEN
        RAISE EXCEPTION 'Run catalogue migrations as orderdesk_migrator';
    END IF;
    IF (SELECT count(*) FROM pg_catalog.pg_roles
        WHERE rolname IN ('orderdesk_app', 'orderdesk_migrator')) <> 2 THEN
        RAISE EXCEPTION 'Provision the two Order Desk database roles first';
    END IF;
    IF EXISTS (
        SELECT 1 FROM pg_catalog.pg_roles
        WHERE rolname IN ('orderdesk_app', 'orderdesk_migrator')
          AND (rolsuper OR rolbypassrls OR rolcreatedb OR rolcreaterole
               OR rolinherit OR rolreplication)
    ) OR EXISTS (
        SELECT 1 FROM pg_catalog.pg_auth_members AS m
        JOIN pg_catalog.pg_roles AS r ON r.oid = m.member
        WHERE r.rolname IN ('orderdesk_app', 'orderdesk_migrator')
    ) OR pg_catalog.has_schema_privilege('orderdesk_app', 'public', 'CREATE') THEN
        RAISE EXCEPTION 'Unsafe Order Desk database role configuration';
    END IF;
END;
$$;
"""

# Keep historical policy definitions in the migration, independent of live code.
# Every interpolated fragment below is a fixed SQL constant, never external input.
TENANT_RULE = """
catalog_catalogitem.organization_id =
    NULLIF(pg_catalog.current_setting('orderdesk.organization_id', true), '')::uuid
AND EXISTS (
    SELECT 1
    FROM public.organizations_membership AS m
    JOIN public.organizations_organization AS o ON o.id = m.organization_id
    JOIN public.accounts_user AS u ON u.id = m.user_id
    WHERE m.organization_id = catalog_catalogitem.organization_id
      AND m.user_id =
          NULLIF(pg_catalog.current_setting('orderdesk.user_id', true), '')::uuid
      AND m.is_active AND o.is_active AND u.is_active
)
"""

ADMIN_RULE = """
EXISTS (
    SELECT 1 FROM public.organizations_membership AS m
    WHERE m.organization_id = catalog_catalogitem.organization_id
      AND m.user_id =
          NULLIF(pg_catalog.current_setting('orderdesk.user_id', true), '')::uuid
      AND m.is_active AND m.role = 'admin'
)
"""

INSTALL_RLS = f"""
ALTER TABLE public.catalog_catalogitem ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalog_catalogitem FORCE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.catalog_catalogitem FROM PUBLIC, orderdesk_app;
GRANT SELECT, INSERT, UPDATE ON TABLE public.catalog_catalogitem TO orderdesk_app;

CREATE POLICY catalog_tenant_boundary ON public.catalog_catalogitem
    AS RESTRICTIVE FOR ALL TO orderdesk_app
    USING ({TENANT_RULE}) WITH CHECK ({TENANT_RULE});
CREATE POLICY catalog_member_read ON public.catalog_catalogitem
    AS PERMISSIVE FOR SELECT TO orderdesk_app USING (true);
CREATE POLICY catalog_admin_insert ON public.catalog_catalogitem
    AS PERMISSIVE FOR INSERT TO orderdesk_app WITH CHECK ({ADMIN_RULE});
CREATE POLICY catalog_admin_update ON public.catalog_catalogitem
    AS PERMISSIVE FOR UPDATE TO orderdesk_app
    USING ({ADMIN_RULE}) WITH CHECK ({ADMIN_RULE});
CREATE POLICY catalog_owner_maintenance ON public.catalog_catalogitem
    AS PERMISSIVE FOR ALL TO orderdesk_migrator
    USING (true) WITH CHECK (true);
"""

REMOVE_RLS = """
REVOKE ALL ON TABLE public.catalog_catalogitem FROM orderdesk_app;
DROP POLICY catalog_owner_maintenance ON public.catalog_catalogitem;
DROP POLICY catalog_admin_update ON public.catalog_catalogitem;
DROP POLICY catalog_admin_insert ON public.catalog_catalogitem;
DROP POLICY catalog_member_read ON public.catalog_catalogitem;
DROP POLICY catalog_tenant_boundary ON public.catalog_catalogitem;
ALTER TABLE public.catalog_catalogitem NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.catalog_catalogitem DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    initial = True
    atomic = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(require_postgresql, require_postgresql),
        migrations.RunSQL(ROLE_GUARD, reverse_sql=migrations.RunSQL.noop),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.TextField(validators=[django.core.validators.RegexValidator('\\S', 'Enter a nonblank stock code.')])),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_items', to='organizations.organization')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('sku__regex', '\\S')), name='catalog_sku_not_blank'), models.UniqueConstraint(fields=('organization', 'sku'), name='catalog_org_sku_unique')],
            },
        ),
        migrations.RunSQL(INSTALL_RLS, reverse_sql=REMOVE_RLS),
    ]
