import test from 'node:test';
import assert from 'node:assert/strict';
import { ApiClient, ApiError } from '../assets/desk/api.js';
import { DocumentController, MAX_DOCUMENT_BYTES, documentRoute } from '../assets/desk/documents.js';
import { parseRoute } from '../assets/desk/orders-api.js';
const w = '11111111-1111-1111-1111-111111111111', o = '22222222-2222-2222-2222-222222222222', d = '33333333-3333-3333-3333-333333333333';
const row = { id: d, organization: w, order: o, original_name: '<img src=x>.pdf', size_bytes: 4, content_type: 'application/pdf', status: 'received', download_url: `/api/v1/workspaces/${w}/orders/${o}/documents/${d}/download/` };
function fixture(request = async () => ({ count: 1, results: [row] }), role = 'admin') { const client = { request, refreshCsrf: async () => {} }; const denied = []; const desk = new DocumentController(client, () => {}, async action => denied.push(action)); desk.context({ id: w, role }, 1, o); return { desk, client, denied }; }
test('document routes identify purchase orders rather than source drafts', () => { assert.deepEqual(parseRoute(documentRoute(w, o)), { screen: 'documents', workspace: w, order: o }); assert.equal(parseRoute(documentRoute(w)).screen, 'documents'); assert.equal(parseRoute(`#/workspaces/${w}/orders/not-valid/documents/`).screen, 'missing'); });
test('FormData uses cookie credentials and CSRF without an invented multipart boundary', async () => { let options; const api = new ApiClient(async (_path, supplied) => { options = supplied; return { ok: true, status: 201, json: async () => row }; }); api.csrf = 'fresh'; const form = new FormData(); form.append('file', new File(['pdf'], 'source.pdf')); await api.request('/api/v1/workspaces/', { method: 'POST', body: form }); assert.equal(options.body, form); assert.equal(options.headers['Content-Type'], undefined); assert.equal(options.headers['X-CSRFToken'], 'fresh'); assert.equal(options.credentials, 'same-origin'); });
test('file picker rejects empty, oversized and unsupported inputs; viewer cannot upload', () => { const { desk } = fixture(); for (const file of [new File([], 'empty.pdf'), { name: 'huge.csv', size: MAX_DOCUMENT_BYTES + 1 }, new File(['html'], 'evil.html')]) { desk.select(file); assert.equal(desk.state.file, null); assert.match(desk.state.message, /Choose/); } const viewer = fixture(undefined, 'viewer').desk; viewer.select(new File(['pdf'], 'source.pdf')); assert.equal(Boolean(viewer.canUpload()), false); });
test('status pages are bounded and reject cross-tenant metadata and unsafe links', async () => { for (const changed of [{ ...row, organization: o }, { ...row, order: d }, { ...row, status: 'extracted' }, { ...row, download_url: 'https://other.test/' }]) { const { desk } = fixture(async () => ({ count: 1, results: [changed] })); await desk.list(); assert.deepEqual(desk.state.rows, []); assert.match(desk.state.message, /unavailable/); } });
test('pending upload suppresses duplicate POST and successful response refreshes received status', async () => { let resolve, calls = 0; const { desk, client } = fixture(async (_path, options) => { if (options.method === 'POST') { calls++; return new Promise(done => { resolve = done; }); } return { count: 1, results: [row] }; }); desk.select(new File(['1234'], 'source.pdf')); const pending = desk.upload(); await new Promise(done => setImmediate(done)); await desk.upload(); assert.equal(calls, 1); assert.equal(desk.state.pending, true); resolve(row); await pending; assert.equal(desk.state.rows[0].status, 'received'); assert.equal(desk.state.file, null); assert.match(desk.state.message, /No extraction/); });
test('validation keeps file context; uncertain network outcome blocks automatic retries', async () => { for (const error of [new ApiError(400, { file: ['Malformed.'] }), new TypeError('lost response')]) { let calls = 0; const { desk } = fixture(async () => { calls++; throw error; }); desk.select(new File(['1234'], 'source.pdf')); await desk.upload(); assert.ok(desk.state.file); if (!(error instanceof ApiError)) { await desk.upload(); assert.equal(calls, 1); assert.equal(desk.state.uncertain, true); assert.match(desk.state.message, /unconfirmed/); } else assert.match(desk.state.message, /Malformed/); } });
test('late status/upload/download responses cannot repopulate another workspace/session', async () => { for (const operation of ['list', 'upload', 'download']) { let resolve; const { desk } = fixture(async () => new Promise(done => { resolve = done; })); if (operation === 'upload') desk.select(new File(['1234'], 'source.pdf')); const pending = operation === 'list' ? desk.list() : operation === 'upload' ? desk.upload() : desk.download(row); await new Promise(done => setImmediate(done)); desk.context(null, 2); resolve(operation === 'list' ? { count: 1, results: [row] } : operation === 'upload' ? row : new Blob(['1234'])); const result = await pending; assert.deepEqual(desk.state.rows, []); assert.equal(desk.state.file, null); if (operation === 'download') assert.equal(result, null); } });
test('download retains exact bytes, validates size and preserves review status', async () => { const { desk } = fixture(async () => new Blob(['1234'])); const blob = await desk.download(row); assert.equal(await blob.text(), '1234'); assert.match(desk.state.message, /does not change review/); desk.client.request = async () => new Blob(['truncated']); assert.equal(await desk.download(row), null); });
test('role/action denial rechecks access without treating every denial as logout', async () => { const { desk, denied } = fixture(async () => { throw new ApiError(403, { detail: 'Denied.' }); }); desk.select(new File(['1234'], 'source.pdf')); await desk.upload(); assert.deepEqual(denied, [true]); await desk.list(); assert.deepEqual(denied, [true, false]); });
